# Generated by Django 5.0.4 on 2024-04-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0004_alter_campagne_montant_alter_campagne_supporteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='supporteurs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
