# Generated by Django 5.0.4 on 2024-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagne', '0005_alter_campagne_montant_alter_campagne_supporteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='supporteurs',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
